apiVersion: v1
kind: ConfigMap
metadata:
  name: search-elastic-config
  labels:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "search.fullname" . }}"
data:
  host: "{{ template "search.elasticsearch.uname" . }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-redis-config
  labels:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "search.fullname" . }}"
data:
  host: "{{ template "search.api.redis.fullname" . }}"
  port: "6379"
  graph: "test"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-data-config
  labels:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "search.fullname" . }}"
data:
  data_directory: "/opt/airflow/share/data"
  tranql_endpoint: "http://{{ template "search.tranql.fullname" . }}:{{ .Values.tranql.port }}{{ .Values.tranql.webPrefix }}/tranql/query?dynamic_id_resolution=true&asynchronous=false"