{{- if not (lookup "v1" "PersistentVolumeClaim" .Release.Namespace ( "search-data" )) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-data
  # Prevents deletion on helm uninstall.
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.pvcSize }}
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redis.tplValue" (dict "value" .Values.redis.persistence.existingClaim "context" $) }}
  annotations:
    # makes sure that pvc is created before job.
    "helm.sh/hook": pre-install
    # makes sure that pvc is created before job.
    "helm.sh/hook-weight": "-6"
    "helm.sh/resource-policy": keep
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany