apiVersion: v1
kind: Secret
metadata:
  {{- $elasticSecretName := printf "%s-%s" .Release.Name "elastic-secret" }}
  name: {{ $elasticSecretName }}
{{- if or .Release.IsInstall ( not (lookup "v1" "Secret" .Release.Namespace ( $elasticSecretName ))) }}
stringData:
  username: elastic
data:
  {{ .Values.secrets.elastic.userKey }}: {{ "elastic" | b64enc | quote }}
  {{ .Values.secrets.elastic.passwordKey }}: {{ randAlphaNum 10 | b64enc | quote }}
{{- else }}
data:
  {{ .Values.secrets.elastic.userKey }}: {{ index (lookup "v1" "Secret" .Release.Namespace ( .Values.secrets.elastic.name )).data .Values.secrets.elastic.userKey }}
  {{ .Values.secrets.elastic.passwordKey }}: {{ index (lookup "v1" "Secret" .Release.Namespace ( .Values.secrets.elastic.name )).data .Values.secrets.elastic.passwordKey }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "redis-secret" }}
data:
  {{- if or .Release.IsInstall ( not (lookup "v1" "Secret" .Release.Namespace ( .Values.secrets.redis.name ))) }}
  {{ .Values.secrets.redis.passwordKey }}: {{ randAlphaNum 10 | b64enc | quote }}
  {{ else }}
  {{ .Values.secrets.redis.passwordKey }}: {{ index (lookup "v1" "Secret" .Release.Namespace ( .Values.secrets.redis.name )).data .Values.secrets.redis.passwordKey }}
  {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.airflow.airflow.configSecretsName }}
data:
  {{- if or .Release.IsInstall (not ( lookup "v1" "Secret" .Release.Namespace ( .Values.airflow.airflow.configSecretsName ) ))  }}
  fernet-key: {{ randAlphaNum 10 | b64enc | quote }}
  {{ else }}
  fernet-key: {{ index (lookup "v1" "Secret" .Release.Namespace ( .Values.airflow.airflow.configSecretsName )).data "fernet-key" }}
  {{ end }}