apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.ui.app_name }}
  name: {{ include "search.ui.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.ui.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ui.app_name }}
    spec:
      {{- with .Values.ui.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        name: {{ include "search.ui.fullname" . }}-container
        ports:
          - containerPort: {{ .Values.ui.container_port }}
        env:
          - name: REACT_APP_DUG_URL
            value: {{ .Values.ui.api_url }}
          {{- if .Values.ui.extraEnv }}
          {{ toYaml .Values.ui.extraEnv | nindent 10 }}
          {{- end }}
        resources:
          {{- toYaml .Values.ui.resources | nindent 10 }}