name: check-helm-dependencies
on:
  # schedule:
  # # Every sunday at midnight UTC time
  #   - cron: '0 0 \* \* 0'
  push:

jobs:
  trigger-helm-charts:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }} 
        # fetch-depth: 0 means, get all branches and commits
        fetch-depth: 0

    # - name: Install jq
    #   run: sudo apt-get update && sudo apt-get install -y jq

    - name: Helm Dependecy Update 
      run: | 
        helm repo add helx-charts https://helxplatform.github.io/helm-charts
        helm repo update
        helm dependency update

    - name: Install helm-images plugin
      run: | 
        helm plugin install https://github.com/nikhilsbhat/helm-images

    - name: Generate report of image versions 
      run: |
        for i in $(ls ./charts) 
        do 
          helm images get $i --no-color >> /tmp/image_report.txt 2> /dev/null
        done  

    - name: Print out report 
      run: | 
        cat /tmp/image_report.txt 


# https://cli.github.com/manual/gh_pr_create
# use github tool to create the PR

    # - name: Create New CI Pull Request
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     gh pr create \
    #       --fill --base develop \
    #       --head actions/${{ steps.package.outputs.package }} \
    #       --reviewer ${{ inputs.actor }} \
    #       --reviewer pj-linebaugh
    #       --reviewer waTeim \
    #       --reviewer YaphetKG